// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// z_constructor
arma::cube z_constructor(const arma::mat& covariates, const int& S, const int& N, const int& p);
RcppExport SEXP _BRdac_z_constructor(SEXP covariatesSEXP, SEXP SSEXP, SEXP NSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type covariates(covariatesSEXP);
    Rcpp::traits::input_parameter< const int& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const int& >::type N(NSEXP);
    Rcpp::traits::input_parameter< const int& >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(z_constructor(covariates, S, N, p));
    return rcpp_result_gen;
END_RCPP
}
// logPCL_BR_thresh
double logPCL_BR_thresh(const double& alpha, const double& phi, const double& u_1, const double u_2, const arma::mat& x, const arma::vec& loc_1, const arma::vec& loc_2);
RcppExport SEXP _BRdac_logPCL_BR_thresh(SEXP alphaSEXP, SEXP phiSEXP, SEXP u_1SEXP, SEXP u_2SEXP, SEXP xSEXP, SEXP loc_1SEXP, SEXP loc_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const double& >::type u_1(u_1SEXP);
    Rcpp::traits::input_parameter< const double >::type u_2(u_2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type loc_1(loc_1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type loc_2(loc_2SEXP);
    rcpp_result_gen = Rcpp::wrap(logPCL_BR_thresh(alpha, phi, u_1, u_2, x, loc_1, loc_2));
    return rcpp_result_gen;
END_RCPP
}
// logCL_BR_thresh
double logCL_BR_thresh(const arma::vec& par, const arma::vec& thresholds, const arma::mat& x, const arma::mat& locs);
RcppExport SEXP _BRdac_logCL_BR_thresh(SEXP parSEXP, SEXP thresholdsSEXP, SEXP xSEXP, SEXP locsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type thresholds(thresholdsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type locs(locsSEXP);
    rcpp_result_gen = Rcpp::wrap(logCL_BR_thresh(par, thresholds, x, locs));
    return rcpp_result_gen;
END_RCPP
}
// Cscore_BR_thresh
arma::mat Cscore_BR_thresh(const arma::vec& par, const double& u, const arma::mat& x, const arma::mat& locs);
RcppExport SEXP _BRdac_Cscore_BR_thresh(SEXP parSEXP, SEXP uSEXP, SEXP xSEXP, SEXP locsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const double& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type locs(locsSEXP);
    rcpp_result_gen = Rcpp::wrap(Cscore_BR_thresh(par, u, x, locs));
    return rcpp_result_gen;
END_RCPP
}
// logPCL_all_thresh
double logPCL_all_thresh(const double& alpha, const double& phi, const arma::vec& beta_1, const arma::vec& beta_2, const arma::vec& beta_3, const double& u_1, const double& u_2, const arma::mat& y, const arma::mat& z_1_1, const arma::mat& z_2_1, const arma::mat& z_3_1, const arma::mat& z_1_2, const arma::mat& z_2_2, const arma::mat& z_3_2, const arma::vec& loc_1, const arma::vec& loc_2);
RcppExport SEXP _BRdac_logPCL_all_thresh(SEXP alphaSEXP, SEXP phiSEXP, SEXP beta_1SEXP, SEXP beta_2SEXP, SEXP beta_3SEXP, SEXP u_1SEXP, SEXP u_2SEXP, SEXP ySEXP, SEXP z_1_1SEXP, SEXP z_2_1SEXP, SEXP z_3_1SEXP, SEXP z_1_2SEXP, SEXP z_2_2SEXP, SEXP z_3_2SEXP, SEXP loc_1SEXP, SEXP loc_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_1(beta_1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_2(beta_2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_3(beta_3SEXP);
    Rcpp::traits::input_parameter< const double& >::type u_1(u_1SEXP);
    Rcpp::traits::input_parameter< const double& >::type u_2(u_2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type z_1_1(z_1_1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type z_2_1(z_2_1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type z_3_1(z_3_1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type z_1_2(z_1_2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type z_2_2(z_2_2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type z_3_2(z_3_2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type loc_1(loc_1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type loc_2(loc_2SEXP);
    rcpp_result_gen = Rcpp::wrap(logPCL_all_thresh(alpha, phi, beta_1, beta_2, beta_3, u_1, u_2, y, z_1_1, z_2_1, z_3_1, z_1_2, z_2_2, z_3_2, loc_1, loc_2));
    return rcpp_result_gen;
END_RCPP
}
// logCL_all_thresh
double logCL_all_thresh(const arma::vec& par, const arma::vec& thresholds, const arma::mat& y, const arma::cube& z_1, const arma::cube& z_2, const arma::cube& z_3, const arma::mat& locs);
RcppExport SEXP _BRdac_logCL_all_thresh(SEXP parSEXP, SEXP thresholdsSEXP, SEXP ySEXP, SEXP z_1SEXP, SEXP z_2SEXP, SEXP z_3SEXP, SEXP locsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type thresholds(thresholdsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type z_1(z_1SEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type z_2(z_2SEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type z_3(z_3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type locs(locsSEXP);
    rcpp_result_gen = Rcpp::wrap(logCL_all_thresh(par, thresholds, y, z_1, z_2, z_3, locs));
    return rcpp_result_gen;
END_RCPP
}
// Chessian_all_thresh
List Chessian_all_thresh(const arma::vec& par, const arma::vec& thresholds, const arma::mat& y, const arma::cube& z_1, const arma::cube& z_2, const arma::cube& z_3, const arma::mat& locs);
RcppExport SEXP _BRdac_Chessian_all_thresh(SEXP parSEXP, SEXP thresholdsSEXP, SEXP ySEXP, SEXP z_1SEXP, SEXP z_2SEXP, SEXP z_3SEXP, SEXP locsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type thresholds(thresholdsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type z_1(z_1SEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type z_2(z_2SEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type z_3(z_3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type locs(locsSEXP);
    rcpp_result_gen = Rcpp::wrap(Chessian_all_thresh(par, thresholds, y, z_1, z_2, z_3, locs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BRdac_z_constructor", (DL_FUNC) &_BRdac_z_constructor, 4},
    {"_BRdac_logPCL_BR_thresh", (DL_FUNC) &_BRdac_logPCL_BR_thresh, 7},
    {"_BRdac_logCL_BR_thresh", (DL_FUNC) &_BRdac_logCL_BR_thresh, 4},
    {"_BRdac_Cscore_BR_thresh", (DL_FUNC) &_BRdac_Cscore_BR_thresh, 4},
    {"_BRdac_logPCL_all_thresh", (DL_FUNC) &_BRdac_logPCL_all_thresh, 16},
    {"_BRdac_logCL_all_thresh", (DL_FUNC) &_BRdac_logCL_all_thresh, 7},
    {"_BRdac_Chessian_all_thresh", (DL_FUNC) &_BRdac_Chessian_all_thresh, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_BRdac(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
