# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

z_constructor <- function(covariates, S, N, p) {
    .Call(`_BRdac_z_constructor`, covariates, S, N, p)
}

logPCL_BR_thresh <- function(alpha, phi, u_1, u_2, x, loc_1, loc_2) {
    .Call(`_BRdac_logPCL_BR_thresh`, alpha, phi, u_1, u_2, x, loc_1, loc_2)
}

logCL_BR_thresh <- function(par, thresholds, x, locs) {
    .Call(`_BRdac_logCL_BR_thresh`, par, thresholds, x, locs)
}

Cscore_BR_thresh <- function(par, u, x, locs) {
    .Call(`_BRdac_Cscore_BR_thresh`, par, u, x, locs)
}

logPCL_all_thresh <- function(alpha, phi, beta_1, beta_2, beta_3, u_1, u_2, y, z_1_1, z_2_1, z_3_1, z_1_2, z_2_2, z_3_2, loc_1, loc_2) {
    .Call(`_BRdac_logPCL_all_thresh`, alpha, phi, beta_1, beta_2, beta_3, u_1, u_2, y, z_1_1, z_2_1, z_3_1, z_1_2, z_2_2, z_3_2, loc_1, loc_2)
}

logCL_all_thresh <- function(par, thresholds, y, z_1, z_2, z_3, locs) {
    .Call(`_BRdac_logCL_all_thresh`, par, thresholds, y, z_1, z_2, z_3, locs)
}

Chessian_all_thresh <- function(par, thresholds, y, z_1, z_2, z_3, locs) {
    .Call(`_BRdac_Chessian_all_thresh`, par, thresholds, y, z_1, z_2, z_3, locs)
}

